version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo updating npm and awscli...
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Installing node dependencies...
      - npm install
      - cd client && npm install       
  build:
    commands:
      - echo Building static files
      - npm run build
  post_build:
    commands:
      - echo Finished build on s3 on `date`
      #- aws s3 sync build s3://jpaulino.com/
#artifacts:
#    files: imagedefinitions.json